### ISSUE TITLE
Criar projeto inicial

### ISSUE THREAD

**Issue by brunoreginato** [demarte/open-weather#1]
- [x] Criar projeto inicial
- [x] Criar `README.md` com:
  - Idea do projeto
  - API que será consumida (https://openweathermap.org/)
  - Qual code-style seguiremos? (https://github.com/raywenderlich/swift-style-guide)
- [x] Criar um template de PR com o conteudo:

```
Fixes: #ID_DA_ISSUE

### Descrição:
<!-- O que mudamos nesse PR? -->

### Testes:
<!-- Quais os casos de teste executamos para garantir que não quebramos nada? -->

- [ ] O projeto funciona após minhas mudanças
...

### Screenshoots:
<!-- Caso necessário, adicionar screenshoots da mudança-->

```
[Tutorial, Github](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

**Comment by demarte** [comment]
Agora sobre a issue, eu marquei as opções como finalizadas. Sobre a branch demarte/1 que ja foi "mergeada" devo deleta-la?

**Comment by brunoreginato** [comment]
Sim! Pode deleta-la

**Comment by brunoreginato** [comment]
@demarte Não se esqueça de fechar as issues que já fizemos o merge
