### ISSUE TITLE
Criar API para salvar localmente cidades

### ISSUE THREAD

**Issue by brunoreginato** [demarte/open-weather#12]
Essa tarefa é pré-requisito para a tarefa de UI da tela de lista de cidades: #13
A tela de lista de cidades precisará de uma camada de acesso aos dados.
Seguindo nossas ideias de `Provider`/`Service` a mesma necessitará dessas camadas.

A ideia é criar um CRUD simples, local, para persistir as cidades.

**Comment by demarte** [comment]
Pra persistência eu devo utilizar o Core Data?

**Comment by brunoreginato** [comment]
Pode ser! Da uma olhada no Realm tmb!
