### ISSUE TITLE
Criar tela de "soft ask" para pedir a localização do usuário

### ISSUE THREAD

**Issue by brunoreginato** [demarte/open-weather#6]
## Descrição:
Desenvolver tela com o soft ask da location.
- Essa tela será exibida somente a primeira vez que o usuário entrar na app.
- Caso o usuário de o tap no "Yes", mostrar o alert nativo pedindo para ter acesso a location do usuário.
- Caso o usuário de o tap no "Maybe later", redirecionar para lista vazia de cidades (será desenvolvida no futuro)

## Mock:
<img width="323" alt="screen shot 2019-02-12 at 18 45 57" src="https://user-images.githubusercontent.com/5031753/52666843-7ae26280-2ef6-11e9-9071-1b3b9d3605ff.png">

**PS.:** Usar apenas componentes nativos

**Comment by demarte** [comment]
Bruno, vc sabe qual é o nome dessa fonte?

**Comment by brunoreginato** [comment]
Pode usar a padrão do iOS (`SF`) que você automaticamente seta usando o estilo `System` nas labels/buttons.

![image](https://user-images.githubusercontent.com/5031753/52720759-6605dd80-2f8f-11e9-9604-8a317bb8b6e6.png)

**Comment by demarte** [comment]
Como havíamos conversado, estou fazendo essa tela programaticamente, só que ainda estou com umas duvidas sobre boas praticas. A principal no momento é onde agrupar os códigos das constraints. Por enquanto esta tudo no view controller. Poderia me dar uma dica?

**Comment by brunoreginato** [comment]
Vamos lá...

Normalmente é responsabilidade do próprio `UIViewController` criar e configurar as subviews. Caso você veja que existe a possibilidade de sub-dividir esse controller em componentes, nós criamos novos controllers e os adicionamo-nos como `childViewControllers.`

## Importante ponto sobre layout via código:

Um dos motivos pelo qual prefiro fazer layout via código é o fato de ser o "dono" daquela instancia do viewController

> Mas o que é ser o dono de uma instancia?
Na minha visão, ser o dono de uma instancia é ter a possibilidade de chamar o construtor daquele classe e poder configura-lo da melhor forma.

### Como fazemos isso via storyboard?
`UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "MyViewController")`

Perceba que é só peço a instancia a API da Apple que chamará o construtor internamente.

### Como fazemos isso via código?
`MyViewController()`

> Ahh mas isso é frescura, nem parece ser tãooo problematico...

Veja, isso é simples quando não temos nenhuma dependência com aquele view controller, agora vamos imaginar como faríamos isso, caso esse viewController dependesse de um `Service` por exemplo...

**Storyboard**
```Swift
let myViewController = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: "MyViewController")
myViewController.configureDependencies(reachabilityService: reachabilityService,
userService: userService)
```

**Código**
```Swift
MyViewController(reachabilityService: reachabilityService, userService: userService)
```
Percebe como o construtor está sendo usado para seu propósito? **CONSTRUIR** o objeto e **DEFINIR** as dependências para a construção do mesmo?

De uma forma narrativa, podemos dizer que o construtor agiria assim: _"Seguinte, pra você construir uma instancia de `MyViewController`, primeiro você me diz qual service de `Reachability` eu devo usar e também qual Service de`user` talkey?"_

Um outro ponto também é: Imagina como essas propriedades ficariam dentro dos respectivos controllers:

**Storyboard**
```Swift
class MyViewController: UIViewController {
   var reachabilityService: ReachabilityServiceType!
   var userService: UserServiceType!

   func configureDependencies(...)
}
```

**Código**
```Swift
class MyViewController: UIViewController {
   let reachabilityService: ReachabilityServiceType
   let userService: UserServiceType

   init(reachabilityService: ReachabilityServiceType, userService: UserServiceType) {
    super...
    ...
   }
}
```
Quando escrevemos o layout via código, explicitamos para qualquer construtor futuro que aquelas dependências PRECISAM ser resolvidas em tempo de alocação daquele objeto.

**Comment by brunoreginato** [comment]
Sobre o fato de organizar o código, vai a minha sugestão:

```Swift
class MyViewController: UIViewController {
   private let titleLabel: UILabel = {
      let label = UILabel()
      label.font = Font.titleFont()
      label.color = Color.titleColor
      return
   }()


   init() {
    ...
    finishInit()
   }

  private func finishInit() {
      setUpTitleLabel()
  }
  private func setUpTitleLabel() {
   view.addSubview(titleLabel)
      // constraints...
  }
}
```

**Comment by demarte** [comment]
Beleza, entendi seu ponto de vista. Também vejo mais vantagens na abordagem via código (sem contar que eu consigo aprender muito mais). O código do TextView, ficou meio grande pq eu usei NSAttributeString pra mudar as configurações da primeira linha em relação as outras. Eu extrai isso para uma outra classe, tipo um custom TextView.

**Comment by demarte** [comment]
No caso dessa tela, são 2 botões. Eu setei 2 propriedades, pois o que muda de uma pra outra é a cor da fonte e o texto. Mas isso não me esta parecendo boa pratica. Se tivéssemos 20 botões num mesmo view controller? Essa é a minha duvida no momento.

**Comment by brunoreginato** [comment]
> O código do TextView, ficou meio grande pq eu usei NSAttributeString pra mudar as configurações da primeira linha em relação as outras. Eu extrai isso para uma outra classe, tipo um custom TextView.

Quando estamos lidando com dados que não receberão inputs do usuario, nós utilizamos instancias do tipo `UILabel`.  `UITextField` e `UITextView` só são utilizados quando estamos esperando que o usuário entre com a alguma informação.

Eu utilizaria duas `UILabels` ao invés de apenas uma.

> No caso dessa tela, são 2 botões. Eu setei 2 propriedades, pois o que muda de uma pra outra é a cor da fonte e o texto. Mas isso não me esta parecendo boa pratica. Se tivéssemos 20 botões num mesmo view controller? Essa é a minha duvida no momento.

Ótimo questionamento. Que tal componentizar esses botões?
Sugiro criar uma pasta `UIComponents` e talvez duas sub-classes de `UIButton`: `PositiveButton` e `NegativeButton`, o que acha?

**Comment by demarte** [comment]
Bom o trabalho foi árduo ate aqui... rs. Eu criei o PR com o que eu fiz no momento para vc avaliar como estou raciocinando a respeito de construir o view controller via código. Acho que componentizar é uma boa sim!

**Comment by demarte** [comment]
Outra coisa. As issues que foram concluídas, eu preciso fechar?
